language: cpp
compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "guH3n3xAMHfWgDMkGymeLOs6VIyBbDHrmeztT5cKmZf2AJp87jmWQOY58IPcUcudWwSK9cxpXZlzk2GtzoSX2Xpi+d2HTzh7rzEpwB1Q4akMKcOtWrlTWT4+vHdt/WOFPNgyh7R7nf5vgmpZFs6de3+9bV1yLsIdrGeqh679jX8="

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev libboost-date-time1.55-dev libboost-chrono1.55-dev libboost-thread1.55-dev libpcsclite-dev libssl-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
script: cat /home/travis/build/islog/liblogicalaccess/cov-int/scm_log.txt | curl -F 'clbin=<-' https://clbin.com && if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir build && pushd build && cmake -DCMAKE_INSTALL_PREFIX=$PWD/install .. && make install && popd && cd samples/basic/ && mkdir build && pushd build && cmake -DLibLogicalAccess_DIR=$PWD/../../../build/install/lib/cmake/liblogicalaccess .. && make ; fi
notifications:
  recipients: reports@islog.com
  
addons:
  coverity_scan:
    project:
      name: "islog/liblogicalaccess"
      description: "Build submitted via Travis CI"
    notification_email: reports@islog.com
    build_command_prepend: "cmake -DCMAKE_INSTALL_PREFIX=$PWD/install ."
    build_command: "make"
    branch_pattern: master
