language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - apt-cache search boost
  - sudo apt-get install -qq libboost1.48-dev libboost-system1.48-dev libboost-filesystem1.48-dev libboost-date-time1.48-dev libpcsclite-dev libssl-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
script: cmake . && make && cd plugins/pluginscards/ && cmake . && make && cd ../pluginsreaderproviders/ && cmake . && make