version: 1.77.3
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0

# branches to build
branches:
  # whitelist
  only:
  - master

# Operating system (build VM template)
os: Windows Server 2012 R2

# clone directory
clone_folder: c:\projects\liblogicalaccess

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
        (new-object System.Net.WebClient).DownloadFile(
          'http://download.islog.com/mavenSettingsAppVeyor.xml',
          'C:\maven\apache-maven-3.2.5\conf\settings.xml'
        )

# scripts to run before build
before_build:
  - cd c:\projects\liblogicalaccess
build_script:
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
